query Compras (
  $Id: Int,
  $UsuarioId: Int,
  $EscenarioId: Int,
  $HoraInicial: String,
  $HoraFinal: String,
  $Tiempo: Int,
  $Abono: Float,
  $Saldo: Float,
  $Estado: String,
  $Fecha: String,
  $Expedicion: String,
  $Hora: String
) {
  Compras (
    Id: $Id,
    UsuarioId: $UsuarioId,
    EscenarioId: $EscenarioId,
    HoraInicial: $HoraInicial,
    HoraFinal: $HoraFinal,
    Tiempo: $Tiempo,
    Abono: $Abono,
    Saldo: $Saldo,
    Estado: $Estado,
    Fecha: $Fecha,
    Expedicion: $Expedicion,
    Hora: $Hora
  ) {
    Id
    UsuarioId
    EscenarioId
    HoraInicial
    HoraFinal
    Tiempo
    Abono
    Saldo
    Estado
    Fecha
    Expedicion
    Hora
    Usuario {
      Id
      Nombre
      Apellido
      Cedula
    }
    Escenario {
      Id
      Nombre
    }
  }
}
