mutation CreateCompra (
  $UsuarioId: Int,
  $EscenarioId: Int,
  $HoraInicial: String,
  $HoraFinal: String,
  $Tiempo: Int,
  $Precio: Float,
  $Estado: String,
  $Fecha: String,
  $Expedicion: String,
  $Hora: String,
) {
  CreateCompra (
    UsuarioId: $UsuarioId,
    EscenarioId: $EscenarioId,
    HoraInicial: $HoraInicial,
    HoraFinal: $HoraFinal,
    Tiempo: $Tiempo,
    Precio: $Precio,
    Estado: $Estado,
    Fecha: $Fecha,
    Expedicion: $Expedicion,
    Hora: $Hora
  ) {
    Id
    UsuarioId
    EscenarioId
    HoraInicial
    HoraFinal
    Tiempo
    Precio
    Estado
    Fecha
    Expedicion
    Hora
    Usuario {
      Id
      Nombre
      Apellido
      Cedula
    }
    Escenario {
      Id
      Nombre
    }
  }
}
