query Escenarios (
  $Id: Int,
  $Tipo: String,
  $Codigo: String,
  $Precio: Float,
  $Activo: String
) {
  Escenarios (
    Id: $Id,
    Tipo: $Tipo,
    Codigo: $Codigo,
    Precio: $Precio,
    Activo: $Activo
  ) {
    Id
    Tipo
    Codigo
    Precio
    Activo
  }
}
