mutation UpdateEscenario (
  $Id: Int,
  $Nombre: String,
  $Imagen: String,
  $Esp1: String,
  $Esp2: String,
  ###$Esp3: String,
  $PrecioDiurno: Float,
  $PrecioNocturno: Float,
  $Likes: Int,
  $Activo: String
) {
  UpdateEscenario (
    Id: $Id,
    Nombre: $Nombre,
    Imagen: $Imagen,
    Esp1: $Esp1,
    Esp2: $Esp2,
    ###Esp3: $Esp3,
    PrecioDiurno: $PrecioDiurno,
    PrecioNocturno: $PrecioNocturno,
    Likes: $Likes,
    Activo: $Activo
  ) {
    Id
    Nombre
    Imagen
    Esp1
    Esp2
    ###Esp3
    Precio
    Likes
    Activo
  }
}
