mutation UsuarioRemoveGrupo(
  $UsuarioId: Int,
  $GrupoId: Int,
) {
  UsuarioRemoveGrupo(
    UsuarioId: $UsuarioId,
    GrupoId: $GrupoId,
  ) {
    Id
    UserName
    Password
    Cedula
    Nombre
    Apellido
    Edad
    Telefono
    Email
    Direccion
    Activo
    Grupos {
      Id
      Nombre
    }
  }
}
